version: '3.1'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.0-management
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13.7
    container_name: postgres_telegram_bot
    hostname: postgres_telega
    environment:
      - POSTGRES_DB=telegram_bot_db
      - POSTGRES_USER=omar
      - POSTGRES_PASSWORD=omar
    ports:
      - "5435:5432"

#  zookeper:
#    image: confluentinc/cp-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOdKEEPER_TICK_TIME: 2000
#    ports:
#      - 2181:2181
#  #
#  kafka:
#    image: confluentinc/cp-kafka
#    depends_on:
#      - zookeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

